# Generated by Django 6.0.1 on 2026-03-25 13:23

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_institution_address_user_institution_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.CharField(default=users.models.generate_uid, editable=False, max_length=15),
        ),
    ]
