# Generated by Django 6.0.1 on 2026-03-27 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_associated_institution_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionjoinrequest',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.department'),
        ),
    ]
