# Generated by Django 6.0.1 on 2026-03-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_institutionjoinrequest_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
