# Generated by Django 6.0.1 on 2026-03-27 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_enrollment_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
