# Generated by Django 6.0.1 on 2026-03-30 07:36

import django.db.models.deletion
import exams.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.IntegerField(help_text='Duration of the exam in minutes')),
                ('pass_percentage', models.FloatField(default=50.0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_randomized', models.BooleanField(default=True, help_text='Randomize question sequence for each student')),
                ('unique_code', models.CharField(default=exams.models.generate_unique_code, help_text='Unique code for students to join the exam', max_length=10, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_students', models.ManyToManyField(blank=True, related_name='authorized_exams', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='users.section')),
                ('study_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='users.studyclass')),
            ],
        ),
        migrations.CreateModel(
            name='ProctoringSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webcam_enabled', models.BooleanField(default=False, help_text='Require webcam access and take periodic snapshots')),
                ('screen_record_enabled', models.BooleanField(default=False, help_text='Require screen sharing')),
                ('full_screen_enforced', models.BooleanField(default=True, help_text='Enforce full screen mode')),
                ('tolerance_count', models.IntegerField(default=3, help_text='Number of warnings before auto-submission')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('TF', 'True/False'), ('DESC', 'Descriptive'), ('CODE', 'Coding')], max_length=10)),
                ('marks', models.FloatField(default=1.0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ONGOING', 'Ongoing'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded')], default='ONGOING', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='exams.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('exam', 'student')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptive_text', models.TextField(blank=True, null=True)),
                ('code_submission', models.TextField(blank=True, null=True)),
                ('marks_obtained', models.FloatField(default=0.0)),
                ('is_graded', models.BooleanField(default=False)),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.option')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.question')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.submission')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=255)),
                ('violation_type', models.CharField(choices=[('NONE', 'None'), ('TAB_SWITCH', 'Tab Switch'), ('FOCUS_LOST', 'Window Focus Lost'), ('COPY_PASTE', 'Copy/Paste Attempt'), ('NO_FACE', 'No Face Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('FULL_SCREEN_EXIT', 'Exited Full Screen')], default='NONE', max_length=30)),
                ('details', models.JSONField(blank=True, null=True)),
                ('snapshot_url', models.URLField(blank=True, max_length=500, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='exams.submission')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Input for the program. Each argument on a new line or formatted appropriately.')),
                ('expected_output', models.TextField(help_text='Expected standard output')),
                ('is_hidden', models.BooleanField(default=True, help_text='Hide this test case from the student during evaluation')),
                ('points', models.FloatField(default=1.0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='exams.question')),
            ],
        ),
        migrations.CreateModel(
            name='ExamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='exams.exam')),
            ],
            options={
                'unique_together': {('exam', 'email')},
            },
        ),
    ]
