# Generated by Django 6.0.1 on 2026-03-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
