# Generated by Django 6.0.2 on 2026-02-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.AddField(
            model_name='exam',
            name='is_randomized',
            field=models.BooleanField(default=True, help_text='Randomize question sequence for each student'),
        ),
    ]
