# Generated by Django 6.0.1 on 2026-02-23 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_question_order_exam_is_randomized'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='snapshot_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='violation_type',
            field=models.CharField(choices=[('NONE', 'None'), ('TAB_SWITCH', 'Tab Switch'), ('FOCUS_LOST', 'Window Focus Lost'), ('COPY_PASTE', 'Copy/Paste Attempt'), ('NO_FACE', 'No Face Detected'), ('MULTIPLE_FACES', 'Multiple Faces Detected'), ('FULL_SCREEN_EXIT', 'Exited Full Screen')], default='NONE', max_length=30),
        ),
        migrations.CreateModel(
            name='ProctoringSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webcam_enabled', models.BooleanField(default=False, help_text='Require webcam access and take periodic snapshots')),
                ('screen_record_enabled', models.BooleanField(default=False, help_text='Require screen sharing')),
                ('full_screen_enforced', models.BooleanField(default=True, help_text='Enforce full screen mode')),
                ('tolerance_count', models.IntegerField(default=3, help_text='Number of warnings before auto-submission')),
                ('exam', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring', to='exams.exam')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(help_text='Input for the program. Each argument on a new line or formatted appropriately.')),
                ('expected_output', models.TextField(help_text='Expected standard output')),
                ('is_hidden', models.BooleanField(default=True, help_text='Hide this test case from the student during evaluation')),
                ('points', models.FloatField(default=1.0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='exams.question')),
            ],
        ),
        migrations.CreateModel(
            name='ExamInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='exams.exam')),
            ],
            options={
                'unique_together': {('exam', 'email')},
            },
        ),
    ]
