# Generated by Django 6.0.1 on 2026-04-04 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_default_inactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='webcam_recording',
            field=models.FileField(blank=True, null=True, upload_to='recordings/'),
        ),
    ]
