# Generated by Django 6.0.1 on 2026-02-25 09:20

import exams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='unique_code',
            field=models.CharField(default=exams.models.generate_unique_code, help_text='Unique code for students to join the exam', max_length=10, unique=True),
        ),
    ]
