# Generated by Django 6.0.1 on 2026-02-25 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_alter_exam_unique_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='authorized_students',
            field=models.ManyToManyField(blank=True, related_name='authorized_exams', to=settings.AUTH_USER_MODEL),
        ),
    ]
